jptv.club:
  FREE:
  - //span/i[@class='fas fa-star text-gold']
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //span[@class='badge-extra text-green']
pthome.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
ptsbao.club:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
totheglory.im:
  FREE:
  - //img[@class='topic'][contains(@src,'ico_free.gif')]
  2XFREE: []
  HR:
  - //img[@src='/pic/hit_run.gif']
  PEER_COUNT:
  - //span[@id='dlstatus']
www.beitai.pt:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdtime.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
kp.m-team.cc:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
lemonhd.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
discfan.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.sjtu.edu.cn:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
nanyangpt.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
audiences.me:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pterclub.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - (//td[@align='left' and @class='rowfollow' and @valign='top']/b[1])[3]
et8.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
pt.keepfrds.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
www.pttime.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  - //h1[@id='top']/b/font[@class='zeroupzerodown']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
1ptba.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
www.tjupt.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //font[@class='twoup'][text()='2X']
  HR:
  - //font[@color='red'][text()='Hit&Run']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdhome.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdsky.me:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
hdcity.city:
  FREE:
  - //img[@class='pro_free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
hdcity.leniter.org:
  FREE:
  - //img[@class='pro_free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
hdcity.work:
  FREE:
  - //img[@class='pro_free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
hdcity4.leniter.org:
  FREE:
  - //img[@class='pro_free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
open.cd:
  FREE:
  - //img[@class='pro_free']
  2XFREE:
  - //img[@class='pro_free2up']
  HR: []
  PEER_COUNT: []
ourbits.club:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.btschool.club:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.eastgame.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.soulvoice.club:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR:
  - //img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
springsunday.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
www.htpt.cc:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
chdbits.co:
  FREE:
  - //h1[@id='top']/img[@class='pro_free']
  2XFREE: []
  HR:
  - //b[contains(text(),'H&R:')]
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdchina.org:
  RENDER: true
  FREE:
  - //h2[@id='top']/img[@class='pro_free']
  2XFREE:
  - //h2[@id='top']/img[@class='pro_free2up']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
ccfbits.org:
  FREE:
  - //font[@color='red'][text()='本种子不计下载量，只计上传量!']
  2XFREE: []
  HR: []
  PEER_COUNT: []
u2.dmhy.org:
  FREE:
  - //td[@class='rowfollow']/img[@class='pro_free'][@alt='FREE']
  2XFREE:
  - //td[@class='rowfollow']/img[@class='pro_free2up'][@alt='2X Free']
  HR: []
  PEER_COUNT: []
www.hdarea.co:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdatmos.club:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
avgv.cc:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
hdfans.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdpt.xyz:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
azusa.ru:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdmayi.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdzone.me:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
gainbound.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
hdvideo.one:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
52pt.site:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.msg.vg:
  LOGIN: user/login/index
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
kamept.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
carpt.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
club.hares.top:
  FREE:
  - //b[@class='free'][text()='免费']
  2XFREE:
  - //b[@class='twoupfree'][text()='2X免费']
  HR: []
  PEER_COUNT: []
www.hddolby.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
piggo.me:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.0ff.cc:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
wintersakura.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
pt.hdupt.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
pt.upxin.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
www.nicept.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
ptchina.org:
  FREE:
  - //h1[@id='top']/b/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
www.hd.ai:
  FREE:
  - //img[@class='pro_free']
  2XFREE: []
  HR: []
  PEER_COUNT: []
hhanclub.top:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
zmpt.cc:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
ihdbits.me:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT: []
leaves.red:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
sharkpt.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
pt.2xfree.org:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
uploads.ltd:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
www.icc2022.com:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
zhuque.in:
  RENDER: true
  FREE:
  - //span[@class='text-download'][contains(text(),'0x')]
  2XFREE:
  - ''
  HR: []
  PEER_COUNT:
  - "//div[@class='ant-form-item-control-input-content']/span[contains(text(),'正在做种:\
    \ )]"
www.oshen.win:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR:
  - //h1[@id='top']/img[@class='hitandrun']
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
cyanbug.net:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
monikadesign.uk:
  FREE:
  - //span[@class='badge-extra'][contains(@data-original-title,'Free')]
  2XFREE: []
  HR: []
  PEER_COUNT:
  - //a[@class='badge-extra text-green'][contains(@data-original-title,'做种')]
skyeysnow.com:
  FREE:
  - //div[@class='pi']/b[contains(text(),'FREE')]
  2XFREE: []
  HR: []
  PEER_COUNT: []
ubits.club:
  FREE:
  - //h1[@id='top']/b/font[@class='free']
  2XFREE:
  - //h1[@id='top']/b/font[@class='twoupfree']
  HR: []
  PEER_COUNT:
  - //div[@id='peercount']/b[1]
