#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function __fixuser {

    echo "以PUID=${PUID}，PGID=${PGID}的身份启动程序..."

    # 更改 nt userid 和 groupid
    groupmod -o -g "$PGID" nt
    usermod -o -u "$PUID" nt

    # 创建目录、权限设置
    if grep -Eqi "Debian" /etc/issue || grep -Eq "Debian" /etc/os-release; then
        chown -R nt:nt /usr/bin/chromedriver
    fi
    chown -R nt:nt "${HOME}" /config /usr/lib/chromium /etc/hosts
    # chown /nas-tools
    chown "${PUID}":"${PGID}" "${WORKDIR}"
    # /nas-tools/下除.git|.github之外 chown
    find "${WORKDIR}" -maxdepth 1 -not \( -path "${WORKDIR}" \) -not \( -path "${WORKDIR}/.git" -prune \) -not \( -path "${WORKDIR}/.github" -prune \) -exec chown -R nt:nt {} \;
    # .git|.github 只在权限不匹配时 chown
    if [ "$(stat -c %u ${WORKDIR}/.git)":"$(stat -c %g ${WORKDIR}/.git)" != "${PUID}":"${PGID}" ]; then
        find "${WORKDIR}/.git" ! -user "${PUID}" -a ! -group "${PGID}" -exec chown "${PUID}":"${PGID}" {} \;
        find "${WORKDIR}/.github" ! -user "${PUID}" -a ! -group "${PGID}" -exec chown "${PUID}":"${PGID}" {} \;
    fi

}

__fixuser 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"