id: 1337x
name: 1337x
domain: https://1337x.to/
encoding: UTF-8
public: true
proxy: true
language: en
search:
  paths:
  - path: search/{keyword}/1/
    method: get
torrents:
  list:
    selector: div.table-list-wrap > table > tbody > tr
  fields:
    id:
      selector: td.name > a[href*="/torrent/"]
      attribute: href
      filters:
      - name: re_search
        args: [\d+, 0]
    title:
      selector: td.name > a[href*="/torrent/"]
    details:
      selector: td.name > a[href*="/torrent/"]
      attribute: href
    download:
      detail:
        xpath: //a[contains(@href, "magnet:")]/@href
    date_added:
      selector: td.coll-date
    size:
      selector: td.size
    seeders:
      selector: td.seeds
    leechers:
      selector: td.leeches
    grabs:
      selector: td.user
    downloadvolumefactor:
      case:
        '*': 0
    uploadvolumefactor:
      case:
        '*': 1
