id: gaoqing
name: 高清电台
domain: https://gaoqing.fm/
encoding: UTF-8
public: true
proxy: false
search:
  paths:
  - path: s.php?q={keyword}
    method: get
torrents:
  list:
    selector: div.col-md-9 > ul.item-list.nav > div.row
  fields:
    id:
      selector: tr.js-search-results-row
      attribute: data-itemindex
    title:
      selector: div.col-md-9 > div > a[href*="https://gaoqing.fm/view/"] > h4
    details:
      selector: div.col-md-9 > div > a[href*="https://gaoqing.fm/view/"]
      attribute: href
    download:
      detail:
        xpath: //table[@id="cili"]//a[@rel="nofollow"]/@href
    downloadvolumefactor:
      case:
        '*': 0
    uploadvolumefactor:
      case:
        '*': 1
