id: hdpianyuan
name: 高清片源网
domain: https://www.hdpianyuan.com/
encoding: UTF-8
search:
  paths:
  - path: search.htm?keyword={keyword}
    method: get
torrents:
  list:
    selector: ul.list-unstyled.threadlist > li
  fields:
    title:
      selector: div.media-body > div.subject > a[href*="source-"]
    details:
      selector: div.media-body > div.subject > a[href*="source-"]
      attribute: href
    download:
      detail:
        xpath: //span[@id="link_text_span"]/text()
    date_added:
      selector: div.media-body > div.subject > span:nth-child(2)
    size:
      selector: div.media-body > div.subject > span:nth-child(1)
    description:
      selector: span.filenamespan
    downloadvolumefactor:
      case:
        '*': 0
    uploadvolumefactor:
      case:
        '*': 1
