id: miobt
name: MioBT
domain: https://www.miobt.com/
encoding: UTF-8
public: true
proxy: true
search:
  paths:
  - path: search.php?keyword={keyword}
    method: get
torrents:
  list:
    selector: table.list_style.table_fixed > tbody > tr
  fields:
    title:
      selector: td:nth-child(3) > a
    details:
      selector: td:nth-child(3) > a
      attribute: href
    download:
      detail:
        hash: //span[@id="text_hash_id"]/text()
    date_added:
      selector: td:nth-child(1)
      optional: true
    size:
      selector: td:nth-child(4)
    seeders:
      selector: td:nth-child(5) > span
    leechers:
      selector: td:nth-child(6) > span
    grabs:
      selector: td:nth-child(7) > span
    downloadvolumefactor:
      case:
        '*': 0
    uploadvolumefactor:
      case:
        '*': 1
