id: sharkpt
name: 鲨鱼
domain: https://sharkpt.net/
encoding: UTF-8
public: false
search:
  paths:
  - path: torrents.php
    method: get
  params:
    search: '{keyword}'
  batch:
    delimiter: ' '
    space_replace: _
category:
  movie:
  - {id: 401, cat: Movies, desc: 电影}
  tv:
  - {id: 402, cat: TV/Series, desc: 电视剧}
  - {id: 403, cat: TV/Shows, desc: 综艺}
  - {id: 404, cat: TV/Documentaries, desc: 纪录片}
  - {id: 405, cat: TV/Animations, desc: 动漫}

torrents:
  list:
    selector: div.s-table-body-item > div.torrent-item
  fields:
    id:
      selector: a[href*="details.php?id="]
      attribute: href
      filters:
      - name: re_search
        args: [\d+, 0]
    title:
      selector: div.torrent-title > a
    details:
      selector: div.torrent-title > a
      attribute: href
    download:
      selector: shark-icon.torrent-action-download
      attribute: onclick
      filters:
      - name: re_search
        args: [download.php\?id=\d+, 0]
    size:
      selector: div.torrent-size
    grabs:
      selector: div.torrent-snatches > a
    seeders:
      selector: div.torrent-seeders > a
    leechers:
      selector: div.torrent-leechers > a
    date_elapsed:
      selector: div.torrent-when > span
    date_added:
      selector: div.torrent-when > span
      attribute: title
    date:
      text: "{% if fields['date_elapsed'] or fields['date_added'] %}{{ fields['date_elapsed']\
        \ if fields['date_elapsed'] else fields['date_added'] }}{% else %}now{% endif\
        \ %}"
      filters:
      - name: dateparse
        args: '%Y-%m-%d %H:%M:%S'
    downloadvolumefactor:
      case:
        font.free: 0
        font.twoupfree: 0
        '*': 1
    uploadvolumefactor:
      case:
        font.twoupfree: 2
        '*': 1
    free_deadline:
      default_value: "{% if fields['downloadvolumefactor']==0 %}{{max_time}}{% endif%}"
      default_value_format: '%Y-%m-%d %H:%M:%S.%f'
      selector: div.torrent-tags > font > span
      attribute: title
      filters:
      - name: dateparse
        args: '%Y-%m-%d %H:%M:%S'
    tags:
      selector: div > a.torrents-tag
    description:
      selector: div.torrent-subtitle
    labels:
      selector: div.torrent-tags > span > a.s-tag
