id: zhuque
name: 朱雀
domain: https://zhuque.in/
encoding: UTF-8
parser: TNodeSpider
public: false
search:
  paths:
  - path: torrent/search
    method: chrome
    params:
      keyword: //input[@id="form_item_keyword"]
      submit: //form//button[@type="submit"]
